spring:
  datasource :
    url : jdbc:mysql://localhost:3306/problem3?useUnicode=yes&characterEncoding=UTF-8
    username : root
    password : kishor
    tomcat :
      test-while-idle : true
      max-active : 500
    driver-class-name : com.mysql.cj.jdbc.Driver
    
  jpa :
    show-sql : false
    hibernate :
      ddl-auto : update
      naming :
        strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties : 
      hibernate :
        dialect : org.hibernate.dialect.MySQL5Dialect   

server:
  servlet:
    context-path: /problem3-service
  port: 7002
  
custom:
  base:
    url: http://localhost:7002/problem3-service/
    


      