spring:
  datasource :
    url : jdbc:mysql://localhost:3306/company?useUnicode=yes&characterEncoding=UTF-8
    username : root
    password : kishor
    tomcat :
      test-while-idle : true
      max-active : 500
    driver-class-name : com.mysql.cj.jdbc.Driver
    
  jpa :
    show-sql : false
    hibernate :
      ddl-auto : none
      naming :
        strategy : org.hibernate.cfg.ImprovedNamingStrategy
    properties : 
      hibernate :
        dialect : org.hibernate.dialect.MySQL5Dialect     liquibase:    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true

server:
  servlet:
    context-path: /company-service
  port: 7003
  